version: "3"
services:
  web:
    image: pkrawiec/demo
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8882:8882"
    networks:
      - webnet
networks:
  webnet: